### ISSUE TITLE
Fix stale ED draft?

### ISSUE THREAD

**Issue by cookiecrook** [w3c/graphics-aam#11]
#9 appears to be merged but does not show up in the [editor's draft](https://w3c.github.io/graphics-aam/#mapping_role_table). Date on the ED is 21 July 2021. Does that page need to be republished or is it pointing to a branch other than main?

**Comment by daniel-montalvo** [comment]
Hi @cookiecrook .

I just set up the W3C action for us to be able to automatically publish to the ED once we merge into main. 

Currently Respec is failing because it cannot resolve some definitions.
Please see  https://github.com/w3c/graphics-aam/actions/runs/5098732256/jobs/9166051369

@jnurthen  Is this something you can take a look at?

**Comment by daniel-montalvo** [comment]
Should be fixed now. Clear cache and go to https://w3c.github.io/graphics-aam/
